/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:PlayerTD[MAX_PLAYERS][19];

public OnFilterScriptInit()
{
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 500.000000, 234.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.645833, 11.800008);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 298.500000, 183.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], -741092353);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 396.000000, 228.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 5);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 76.000000, 101.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][1], 2049);
	PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][1], -10.000000, 0.000000, 0.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][1], 1, 1);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 462.000000, 247.000000, "ID");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 470.000000, 258.000000, "NAME");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 470.000000, 272.000000, "DATE");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 479.000000, 285.000000, "ADDRESS");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 478.000000, 299.000000, "EXPIRED");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 502.000000, 247.000000, ":");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 502.000000, 258.000000, ":");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 502.000000, 272.000000, ":");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 502.000000, 285.000000, ":");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

	PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 502.000000, 299.000000, ":");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

	PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 548.000000, 258.000000, "David_Sebastian");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

	PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 534.000000, 272.000000, "12/06/1999");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][13], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

	PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 534.000000, 285.000000, "Jefferson");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][14], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);

	PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 536.000000, 299.000000, "14/08/2022");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][15], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);

	PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 529.000000, 247.000000, "13853132");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 0);

	PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 500.000000, 239.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.645833, -1.999986);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 298.500000, 183.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][17], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 35839);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 0);

	PlayerTD[playerid][18] = CreatePlayerTextDraw(playerid, 500.000000, 227.000000, "IDENTIFICATION_CARD");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][18], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][18], 0.212500, 0.700000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][18], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][18], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][18], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][18], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][18], -1094795726);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][18], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][18], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][0]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][1]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][2]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][3]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][4]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][5]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][6]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][7]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][8]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][9]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][10]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][11]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][12]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][13]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][14]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][15]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][16]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][17]);
	PlayerTextDrawDestroy(playerid, PlayerTD[playerid][18]);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		PlayerTextDrawShow(playerid, PlayerTD[playerid][0]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][1]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][2]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][3]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][4]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][5]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][6]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][7]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][8]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][9]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][10]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][11]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][12]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][13]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][14]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][15]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][16]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][17]);
		PlayerTextDrawShow(playerid, PlayerTD[playerid][18]);
		return 1;
	}
	return 0;
}
